import { type NextPage } from "next";
import Head from "next/head";

import { api } from "y/utils/api";
import { useEffect, useState } from "react";
import Image from "next/image";

const NEW_YORK = { lat: 40.71, lon: 74 };

const Home: NextPage = () => {
  const [location, setLocation] = useState<GeolocationPosition | null>(null);

  useEffect(() => {
    navigator.geolocation.getCurrentPosition((position) => {
      setLocation(position);
    });
  });

  const weather = api.weather.getWeather.useQuery({
    lat: location?.coords.latitude ?? NEW_YORK.lat,
    lon: location?.coords.longitude ?? NEW_YORK.lon,
  });

  return (
    <>
      <Head>
        <title>OTP Weather</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-indigo-900 via-indigo-700 to-pink-300">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-3xl text-white">{weather?.data?.name}</h1>
        </div>
        <div className="text-2xl text-white">
          <h2>Current {weather.data?.main.temp}</h2>
          <h2>Feels like {weather.data?.main.feels_like}</h2>
          <h3>High {weather.data?.main.temp_max}</h3>
          <h3>Low {weather.data?.main.temp_min}</h3>
        </div>
        <div className="rounded-2xl bg-gray-700 shadow-2xl">
          {weather.data?.weather.map((weather) => {
            return (
              <div
                key={weather.id}
                className="flex flex-col items-center justify-center  p-4"
              >
                <h2>{weather.main}</h2>
                <h3>{weather.description}</h3>
                <Image
                  src={`http://openweathermap.org/img/w/${weather.icon}.png`}
                  width={100}
                  height={100}
                  alt=""
                />
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
